import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, MessageSquare, FileText, ChevronRight, Volume2, VolumeX, Flame } from 'lucide-react';
import { useFinance } from '../context/FinanceContext';
import { formatBRL } from '../utils/formatters';
import { fireDopamineConfetti } from '../utils/confetti';
import { dopamineAudio } from '../lib/audio';
import { DuMascotModal } from './DuMascotModal';
import duMascotImg from '../assets/images/du_mascot_avatar_1787750972812.jpg';

export const DuMascot: React.FC = () => {
  const { 
    balanceProjected, 
    savingsRate, 
    duScore, 
    upcomingBills, 
    formattedSelectedMonth 
  } = useFinance();

  const [isAssistantModalOpen, setIsAssistantModalOpen] = useState(false);
  const [modalInitialTab, setModalInitialTab] = useState<'chat' | 'report' | 'simulator' | 'tips'>('chat');

  // Dynamic insight generated by DU based on financial health
  const getDuInsight = () => {
    if (balanceProjected > 2500 && savingsRate >= 25) {
      return {
        mood: 'super_happy',
        title: 'Sensacional! As nozes estão rendendo 🚀',
        text: `Em ${formattedSelectedMonth}, você está poupando ${savingsRate}% (${formatBRL(balanceProjected)} previstos de sobra). Clique para ver seu relatório executivo completo!`,
        badge: 'Poupança Alta 🚀',
        quickTab: 'report' as const
      };
    } else if (balanceProjected > 0) {
      return {
        mood: 'happy',
        title: 'Tudo sob controle no cofre! 🐿️',
        text: `Saldo previsto de ${formatBRL(balanceProjected)} em ${formattedSelectedMonth}. Quer uma dica de ouro para fazer essa sobra render?`,
        badge: 'Fluxo Positivo ✨',
        quickTab: 'chat' as const
      };
    } else if (upcomingBills.length > 0) {
      return {
        mood: 'alert',
        title: 'Atenção aos Vencimentos 💡',
        text: `Você tem ${upcomingBills.length} pagamentos pendentes totalizando ${formatBRL(upcomingBills.reduce((sum, b) => sum + b.amount, 0))}. Mantenha tudo em dia para evitar juros!`,
        badge: 'Alerta de Contas ⚡',
        quickTab: 'chat' as const
      };
    } else {
      return {
        mood: 'neutral',
        title: 'Du está analisando suas finanças 🧐',
        text: 'Converse comigo ou peça um diagnóstico completo para otimizar seus gastos e acelerar sua independência financeira.',
        badge: 'Consultor Du 👔',
        quickTab: 'chat' as const
      };
    }
  };

  const insight = getDuInsight();

  const openWithTab = (tab: 'chat' | 'report' | 'simulator' | 'tips') => {
    setModalInitialTab(tab);
    setIsAssistantModalOpen(true);
    dopamineAudio.playDuGreeting();
  };

  return (
    <>
      {/* 1. Dashboard Executive Banner */}
      <motion.div
        initial={{ y: 12, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        className="relative overflow-hidden rounded-3xl bg-white/90 backdrop-blur-md border border-slate-200/90 p-5 sm:p-6 shadow-xs group"
      >
        {/* Soft background green glow */}
        <div className="absolute top-0 right-0 -mr-16 -mt-16 w-56 h-56 bg-[#21C25E]/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative flex flex-col md:flex-row items-start md:items-center justify-between gap-5">
          
          {/* Mascot Portrait & Insight Text */}
          <div className="flex items-start sm:items-center gap-4 min-w-0">
            
            {/* Interactive Mascot Avatar */}
            <div 
              onClick={() => {
                fireDopamineConfetti();
                dopamineAudio.playDuNut();
                openWithTab('chat');
              }}
              title="Clique para conversar com o Du!"
              className="cursor-pointer group/avatar relative flex-shrink-0"
            >
              <div className="w-16 h-16 sm:w-20 sm:h-20 rounded-2xl bg-white/40 p-1 border-2 border-[#21C25E] shadow-lg shadow-[#21C25E]/20 overflow-hidden group-hover/avatar:scale-105 group-hover/avatar:rotate-2 transition-transform">
                <img 
                  src={duMascotImg} 
                  alt="Du o Mascote" 
                  className="w-full h-full object-cover object-top"
                  referrerPolicy="no-referrer"
                />
              </div>
              <div className="absolute -bottom-1 -right-1 bg-[#21C25E] text-black font-black text-[9px] px-1.5 py-0.5 rounded-full border border-white shadow-xs">
                DU IA
              </div>
            </div>

            {/* Insight text */}
            <div className="min-w-0">
              <div className="flex items-center gap-2 mb-1 flex-wrap">
                <span className="text-xs font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full bg-[#21C25E]/15 text-[#169445] border border-[#21C25E]/30">
                  {insight.badge}
                </span>
              </div>
              
              <h4 className="text-base sm:text-lg font-black text-slate-900 flex items-center gap-1.5 font-['Outfit',sans-serif]">
                {insight.title}
              </h4>
              <p className="text-xs sm:text-sm text-slate-600 max-w-2xl mt-0.5 leading-relaxed font-medium">
                {insight.text}
              </p>
            </div>
          </div>

          {/* Quick Interaction Buttons */}
          <div className="flex flex-wrap items-center gap-2 self-stretch sm:self-auto justify-end flex-shrink-0">
            <button
              onClick={() => openWithTab('chat')}
              className="flex items-center gap-1.5 px-4 py-2.5 rounded-2xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs shadow-xs transition-all hover:scale-105 cursor-pointer"
            >
              <MessageSquare className="w-4 h-4 text-[#21C25E]" />
              <span>Falar com o Du</span>
            </button>

            <button
              onClick={() => openWithTab('report')}
              className="flex items-center gap-1.5 px-4 py-2.5 rounded-2xl bg-[#21C25E] hover:bg-[#1ca650] text-black font-black text-xs shadow-md shadow-[#21C25E]/20 transition-all hover:scale-105 cursor-pointer"
            >
              <FileText className="w-4 h-4 stroke-[2.5]" />
              <span>Relatório Completo</span>
            </button>
          </div>
        </div>
      </motion.div>

      {/* 2. Floating Mascot Widget (Bottom Right) */}
      <div className="fixed bottom-6 right-6 z-40 flex items-center gap-2">
        <motion.div
          initial={{ scale: 0.8, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          className="relative group cursor-pointer"
          onClick={() => openWithTab('chat')}
        >
          {/* Animated floating notification bubble */}
          <div className="absolute -top-10 right-0 bg-white/95 backdrop-blur-md px-3 py-1 rounded-full border border-slate-200 shadow-md text-[11px] font-bold text-slate-800 whitespace-nowrap hidden sm:flex items-center gap-1.5 group-hover:scale-105 transition-transform pointer-events-none">
            <span className="w-2 h-2 rounded-full bg-[#21C25E] animate-ping" />
            <span>Falar com o Du 🐿️</span>
          </div>

          {/* Floating Circle Button */}
          <div className="w-14 h-14 rounded-full bg-slate-900 border-2 border-[#21C25E] p-0.5 shadow-2xl shadow-black/40 flex items-center justify-center overflow-hidden hover:scale-110 active:scale-95 transition-all">
            <img 
              src={duMascotImg} 
              alt="Du Mascot Floating Button" 
              className="w-full h-full object-cover object-top"
              referrerPolicy="no-referrer"
            />
          </div>
        </motion.div>
      </div>

      {/* 3. Mascot Modal Dialog */}
      <DuMascotModal 
        isOpen={isAssistantModalOpen} 
        onClose={() => setIsAssistantModalOpen(false)} 
        initialTab={modalInitialTab}
      />
    </>
  );
};
